### ISSUE TITLE
crashes on iOS7

### ISSUE THREAD

**Issue by stasix** [yahoo/searchsdk-ios#1]
Hi guys,
The search SDK does not work on iOS7. It crashes the app when the results are displayed.

**Comment by jonparis** [comment]
Please send the error you are getting to searchsdk-feedback@yahoo-inc.com and someone will follow up.
Warmly,
Jon

**Comment by stasix** [comment]
Thanks Jon. I sent an error few weeks ago, but did not get an answer.
I will try again.
